#!/usr/bin/env python3
"""Consolidate all Cycle-1 revision results into LaTeX macros + tables for the paper."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent; DATA=ROOT/"data"; TAB=ROOT/"paper"/"tables"
def L(p):
    try: return json.load(open(DATA/p))
    except: return None
rev=L("rev_analysis.json"); irr=L("irr_results.json"); summ=L("rev_summeval_ceiling.json")
sub=L("rev_multipico_subgroup.json"); pr=L("rev_prompt_robustness.json"); cc=L("rev_contamination_control.json")
m={}
def f(x,d=2):
    try: return f"{float(x):.{d}f}"
    except: return str(x)
def pstr(p):
    try:
        p=float(p); return "<.001" if p<1e-3 else f"{p:.2f}"
    except: return str(p)
if irr:
    m.update({"IRRsoneA":f(irr["s1_verdict_alpha_3coder"]),"IRRsoneWone":str(int(irr["s1_within1_orig_c1"]*100)),
      "IRRsoneEx":str(int(irr["s1_exact_orig_c1"]*100)),"IRRsoneN":str(irr["s1_n"]),
      "IRRstwoV":f(irr["s2_verdict_alpha"]),"IRRstwoRole":f(irr["s2_role_alpha"]),
      "IRRstwoStance":f(irr["s2_stance_alpha"]),"IRRstwoN":str(irr["s2_n"])})
if rev:
    g=rev["glmm_crossed"]
    m.update({"GLMsubjOR":f(g["subjectivity_c"]["OR"]),"GLMsubjP":pstr(g["subjectivity_c"]["p"]),
      "GLMbaseOR":f(g["baserate_c"]["OR"],1),"GLMbaseP":pstr(g["baserate_c"]["p"]),
      "GLMsizeOR":f(g["logsize_c"]["OR"]),"GLMsizeP":pstr(g["logsize_c"]["p"]),
      "GLMgranOR":f(g["nclasses_c"]["OR"]),"GLMgranP":pstr(g["nclasses_c"]["p"]),
      "VCitem":f(g["vc_sd"].get("item")),"VCdataset":f(g["vc_sd"].get("dataset")),
      "VCmodel":f(g.get("model_acc_spread"),3),
      "metaSlope":f(rev["meta_regression"]["slope_full"]),"metaLODOmin":f(rev["meta_regression"]["LODO_min"]),
      "metaLODOmax":f(rev["meta_regression"]["LODO_max"]),"metaN":str(rev["meta_regression"]["n_datasets"])})
if summ:
    m.update({"SEfluSD":f(summ["fluency"]["within_doc_sd"]),"SEconSD":f(summ["consistency"]["within_doc_sd"]),
      "SEfluTop":str(int(summ["fluency"]["frac_ratings_ge_4.5"]*100)),"SEfluSelf":f(summ["fluency"]["noiseless_judge_spearman"])})
if sub and "by_gender_gap" in sub:
    m["MPCgenderGap"]=f(sub["by_gender_gap"])
if cc:
    best=max(cc.values(),key=lambda v:v["mean_overlap"])
    m["CCmaxOverlap"]=f(best["mean_overlap"]); m["CCflag"]=best["flag"]
if pr:
    stab=sum(1 for v in pr.values() if v.get("verdict_stable")); tot=len(pr)
    sds=[v["acc_sd"] for v in pr.values()]
    m["PRstable"]=str(stab); m["PRtotal"]=str(tot); m["PRmaxSD"]=f(max(sds)); m["PRmeanSD"]=f(sum(sds)/len(sds))
(TAB/"revision_autostats.tex").write_text("% auto-generated by make_revision_macros.py\n"+
    "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k,v in m.items()))

# disagreement-aware table
if rev:
    rows=[]
    NICE={"ChaosNLI-SNLI":"ChaosNLI-SNLI","ChaosNLI-MNLI":"ChaosNLI-MNLI","GoEmotions":"GoEmotions",
          "SBIC":"SBIC","HateXplain":"HateXplain","MultiPICo":"MultiPICo"}
    for name,d in rev["datasets"].items():
        b=d["best"]; ci=d["ceiling_CI"]
        rows.append(f"{name} & {d['ceiling']:.2f} [{ci[0]:.2f},{ci[1]:.2f}] & {d['kappa'][b]:.2f} & {d['macro_f1'][b]:.2f} & "
                    f"{d['acc_lowEntropy']:.2f} & {d['acc_highEntropy']:.2f} & {d['mean_JS_panel_vs_human']:.2f} \\\\")
    tex=(r"\begin{tabular}{@{}l c c c c c c@{}}"+"\n\\toprule\n"
         r"Dataset & Ceiling [95\% CI] & $\kappa$ & macro-F1 & acc$_{\downarrow H}$ & acc$_{\uparrow H}$ & JS \\"+"\n"
         r" & & (best) & (best) & low-disagr. & high-disagr. & panel-human \\"+"\n\\midrule"+"\n"+"\n".join(rows)+
         "\n\\bottomrule\n\\end{tabular}")
    (TAB/"tab_disagreement.tex").write_text(tex)
print("wrote revision_autostats.tex + tab_disagreement.tex"); print(m)
