#!/usr/bin/env python3
"""Cycle-4 fixes: per-domain-group statistics on a COMMON logit scale, plus a judge-vs-ceiling gap
analysis by item entropy (to test whether the item-disagreement effect is tautological).
Groups: NLI (Paper A) and social-computing (Paper B). No new API calls.
Writes data/rev3_groupstats.json + paper/tables/group_autostats.tex."""
import json, sys, math, warnings
from pathlib import Path
from collections import defaultdict
import numpy as np, pandas as pd
warnings.filterwarnings("ignore")
ROOT=Path(__file__).resolve().parent.parent; OUT=ROOT/"study3"/"outputs"; DATA=ROOT/"data"; TAB=ROOT/"paper"/"tables"
sys.path.insert(0,str(ROOT/"study3")); import harness
GROUPS={"NLI":["chaosnli_snli","chaosnli_mnli"],
        "SOC":["go_emotions","social_bias_frames","hatexplain","multipico"]}
SIZE_B={"qwen3.5-9b":9,"qwen3.6-27b-fp8":27,"gemma-4-31b":31,"gptoss-120b":120,"deepseek-v4-pro":671,"glm-5.1-fp8":754}
def load(key):
    items={}
    for it in harness.LOADERS[key](500):
        items[it["id"]]={"counts":np.array(it["label_count"],float),"gold":it["gold"]}
    preds=defaultdict(dict)
    for l in open(OUT/f"{key}.judgments.jsonl"):
        try: r=json.loads(l)
        except: continue
        if r.get("run_id")=="full" and r.get("pred") is not None: preds[r["item_id"]][r["model"]]=r["pred"]
    return items,preds
def entropy(c):
    p=c/c.sum(); return float(-sum(pi*math.log2(pi) for pi in p if pi>0))
def ceiling_item(c):  # expected random-annotator-vs-majority
    return c.max()/c.sum()
out={}; macros={}
for G,keys in GROUPS.items():
    rows=[]; ent=[]; acc=[]; ceil=[]
    for key in keys:
        items,preds=load(key)
        for i,it in items.items():
            mv=[preds[i][m] for m in preds.get(i,{})]
            if not mv: continue
            a=np.mean([1.0 if v==it["gold"] else 0.0 for v in mv])
            ent.append(entropy(it["counts"])); acc.append(a); ceil.append(ceiling_item(it["counts"]))
            for m in preds.get(i,{}):
                rows.append({"item":f"{key}:{i}","model":m,"correct":int(preds[i][m]==it["gold"]),
                             "logsize":math.log10(SIZE_B[m])})
    df=pd.DataFrame(rows); ent=np.array(ent); acc=np.array(acc); ceil=np.array(ceil)
    # --- variance components on the logit scale (item + model random intercepts) ---
    vc={}
    try:
        from statsmodels.genmod.bayes_mixed_glm import BinomialBayesMixedGLM
        m=BinomialBayesMixedGLM.from_formula("correct ~ 1",{"item":"0+C(item)","model":"0+C(model)"},df)
        r=m.fit_vb(verbose=False)
        vc={nm:float(np.exp(r.vcp_mean[k])) for k,nm in enumerate(r.model.vcp_names)}
    except Exception as e:
        vc={"error":repr(e)[:80]}
    # fallback / cross-check: between-model SD on the LOGIT scale from per-model accuracies
    macc=df.groupby("model")["correct"].mean().clip(1e-3,1-1e-3)
    model_logit_sd=float(np.std(np.log(macc/(1-macc))))
    # --- gap-by-entropy: does the judge-ceiling gap WIDEN on contested items (non-tautological)? ---
    terc=np.quantile(ent,[1/3,2/3])
    def band(e): return 0 if e<=terc[0] else (1 if e<=terc[1] else 2)
    bands=np.array([band(e) for e in ent])
    res_band={}
    for bnd,nm in [(0,"low"),(2,"high")]:
        mask=bands==bnd
        res_band[nm]={"acc":round(float(acc[mask].mean()),3),"ceiling":round(float(ceil[mask].mean()),3),
                      "gap":round(float((acc[mask]-ceil[mask]).mean()),3)}
    out[G]={"vc_logit":{k:round(v,3) for k,v in vc.items()} if "error" not in vc else vc,
            "model_logit_sd":round(model_logit_sd,3),"n_judg":len(df),"n_items":int(df["item"].nunique()),
            "by_entropy":res_band}
    print(f"{G}: vc(logit)={out[G]['vc_logit']} model_logit_sd={model_logit_sd:.3f}")
    print(f"   gap low-entropy={res_band['low']['gap']} (acc {res_band['low']['acc']} vs ceil {res_band['low']['ceiling']}) | "
          f"high-entropy={res_band['high']['gap']} (acc {res_band['high']['acc']} vs ceil {res_band['high']['ceiling']})")
    pre=G
    it_sd=out[G]["vc_logit"].get("item","na") if isinstance(out[G]["vc_logit"],dict) else "na"
    macros[pre+"itemSDlogit"]=str(it_sd)
    macros[pre+"modelSDlogit"]=f"{model_logit_sd:.2f}"
    macros[pre+"gapLow"]=f"{res_band['low']['gap']:+.2f}"; macros[pre+"gapHigh"]=f"{res_band['high']['gap']:+.2f}"
    macros[pre+"accLowE"]=f"{res_band['low']['acc']:.2f}"; macros[pre+"accHighE"]=f"{res_band['high']['acc']:.2f}"
DATA.mkdir(exist_ok=True); json.dump(out,open(DATA/"rev3_groupstats.json","w"),indent=2)
(TAB/"group_autostats.tex").write_text("% auto-generated by rev3_groupstats.py\n"+
    "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k,v in macros.items()))
print("\nwrote data/rev3_groupstats.json + group_autostats.tex"); print(macros)
