#!/usr/bin/env python3
"""Build per-domain-group Study-3 LaTeX tables + macros for the two-paper split, from existing
scores + rev_analysis.json (no re-runs). NLI group -> Paper A; social-computing group -> Paper B."""
import json
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parent.parent; OUT=ROOT/"study3"/"outputs"; TAB=ROOT/"paper"/"tables"
rev=json.load(open(ROOT/"data"/"rev_analysis.json"))["datasets"]
NICEKEY={"chaosnli_snli":"ChaosNLI-SNLI","chaosnli_mnli":"ChaosNLI-MNLI","go_emotions":"GoEmotions",
         "social_bias_frames":"SBIC","hatexplain":"HateXplain","multipico":"MultiPICo"}
NICE2REV=NICEKEY  # rev keys use the nice names
CONS={"chaosnli_snli":"NLI (3-way)","chaosnli_mnli":"NLI (3-way)","go_emotions":"emotion (4-way)",
      "social_bias_frames":"offensive (binary)","hatexplain":"hate (3-way)","multipico":"irony (binary)"}
GROUPS={"nli":["chaosnli_snli","chaosnli_mnli"],
        "social":["go_emotions","social_bias_frames","hatexplain","multipico"]}
esc=lambda s:str(s).replace("&",r"\&").replace("_",r"\_")
sig={"Validated":r"\cellcolor{g!55}","Promising":r"\cellcolor{g!25}","Mixed":r"\cellcolor{a!60}",
     "Caution":r"\cellcolor{r!30}","Unreliable":r"\cellcolor{r!55}"}
from collections import Counter
def build(group,keys):
    rows=[]; nrows=[]; n_judg=0; lowH=[]; highH=[]
    for k in keys:
        s=json.load(open(OUT/f"{k}.full.scores.json")); mods=[m for m in s["models"] if "accuracy" in s["models"][m]]
        accs={m:s["models"][m]["accuracy"] for m in mods}; best=max(accs,key=accs.get)
        bestmf1=s["models"][best].get("macro_f1",float("nan"))
        jury=s.get("jury",{}).get("accuracy",float("nan"))
        vmode=Counter(s["models"][m]["verdict_label"] for m in mods).most_common(1)[0][0]
        nm=NICEKEY[k]; rd=rev[nm]
        ci=rd["ceiling_CI"]
        n_judg+=sum(s["models"][m]["n"] for m in mods)
        rows.append(f"{esc(nm)} & {esc(CONS[k])} & {rd['ceiling']:.2f} & {accs[best]:.2f} ({esc(best.replace('-fp8',''))}) & "
                    f"{bestmf1:.2f} & {jury:.2f} & {sig.get(vmode,'')}{vmode} \\\\")
        nrows.append(f"{esc(nm)} & {rd['ceiling']:.2f} [{ci[0]:.2f},{ci[1]:.2f}] & {rd['kappa'][best]:.2f} & "
                     f"{rd['macro_f1'][best]:.2f} & {rd['acc_lowEntropy']:.2f} & {rd['acc_highEntropy']:.2f} & {rd['mean_JS_panel_vs_human']:.2f} \\\\")
        lowH.append(rd["acc_lowEntropy"]); highH.append(rd["acc_highEntropy"])
    res=(r"\begin{tabular}{@{}l l c c c c l@{}}"+"\n\\toprule\n"
         r"Dataset & Construct & Human & Best model & macro-F1 & Jury & Modal verdict \\"+"\n"
         r" & & ceiling & (acc) & (best) & (acc) & \\"+"\n\\midrule"+"\n"+"\n".join(rows)+"\n\\bottomrule\n\\end{tabular}")
    (TAB/f"tab_{group}_results.tex").write_text(res)
    dis=(r"\begin{tabular}{@{}l c c c c c c@{}}"+"\n\\toprule\n"
         r"Dataset & Ceiling [95\% CI] & $\kappa$ & macro-F1 & acc$_{\downarrow H}$ & acc$_{\uparrow H}$ & JS \\"+"\n"
         r" & & (best) & (best) & low-disagr. & high-disagr. & \\"+"\n\\midrule"+"\n"+"\n".join(nrows)+"\n\\bottomrule\n\\end{tabular}")
    (TAB/f"tab_{group}_disagr.tex").write_text(dis)
    return {"judg":n_judg,"lowH":float(np.mean(lowH)),"highH":float(np.mean(highH)),"ndatasets":len(keys)}
m={}
for g,keys in GROUPS.items():
    r=build(g,keys)
    pre={"nli":"NLI","social":"SOC"}[g]
    m[pre+"njudg"]=f"{r['judg']:,}"; m[pre+"ndat"]=str(r["ndatasets"])
    m[pre+"lowH"]=f"{r['lowH']:.2f}"; m[pre+"highH"]=f"{r['highH']:.2f}"
(TAB/"split_autostats.tex").write_text("% auto-generated by split_tables.py\n"+
    "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k,v in m.items()))
print("wrote tab_nli_results/disagr, tab_social_results/disagr, split_autostats.tex"); print(m)
