#!/usr/bin/env python3
"""Cycle-1 revision: test whether SummEval fluency's low summary-level Spearman is a 'compressed
human reference' (structural) rather than an artifact of integer judge scoring.
For each source document we have 16 human MEAN ratings per aspect. If within-document variance is
near zero (all summaries rated ~equally), then summary-level Spearman is mechanically low for ANY
judge (including a perfect one and including the reported proprietary judge). We measure, per aspect:
mean within-document SD of the human means, the fraction of near-ceiling ratings, and the maximum
attainable summary-level Spearman of a noiseless judge that returns the rounded human integer.
No API calls. Writes data/rev_summeval_ceiling.json + macros."""
import json
from pathlib import Path
import numpy as np
from scipy.stats import spearmanr
from datasets import load_dataset
ROOT=Path(__file__).resolve().parent.parent; DATA=ROOT/"data"; TAB=ROOT/"paper"/"tables"
ASP=["coherence","consistency","fluency","relevance"]
REPORTED={"coherence":0.582,"consistency":0.507,"fluency":0.455,"relevance":0.547}
ds=load_dataset("mteb/summeval",split="test")
per={a:{"within_sd":[],"frac_top":[],"selfcorr":[]} for a in ASP}
for row in ds:
    for a in ASP:
        h=np.array(row[a],float)            # 16 human means for this document
        per[a]["within_sd"].append(float(h.std()))
        per[a]["frac_top"].append(float((h>=4.5).mean()))
        # "perfect" judge = rounded human integer; its summary-level spearman vs the means (ceiling on rankability)
        jr=np.round(h)
        if len(set(jr))>1 and len(set(h))>1:
            r=spearmanr(jr,h).correlation
            if r==r: per[a]["selfcorr"].append(r)
out={}
print(f"{'aspect':12s} {'within-doc SD':>13s} {'frac>=4.5':>10s} {'noiseless-judge rho':>20s} {'reportedG-Eval':>15s}")
for a in ASP:
    sd=float(np.mean(per[a]["within_sd"])); ft=float(np.mean(per[a]["frac_top"])); sc=float(np.mean(per[a]["selfcorr"]))
    out[a]={"within_doc_sd":round(sd,3),"frac_ratings_ge_4.5":round(ft,3),
            "noiseless_judge_spearman":round(sc,3),"reported_geval":REPORTED[a]}
    print(f"{a:12s} {sd:>13.3f} {ft:>10.2f} {sc:>20.3f} {REPORTED[a]:>15.3f}")
# rank aspects by compression
order=sorted(ASP,key=lambda a:out[a]["within_doc_sd"])
out["most_compressed_aspect"]=order[0]
out["note"]="lower within-doc SD => harder to rank => lower attainable summary-level Spearman for ANY judge"
DATA.mkdir(exist_ok=True); json.dump(out,open(DATA/"rev_summeval_ceiling.json","w"),indent=2)
g=lambda x:f"{x:.2f}"
macros={"RVflu_sd":g(out["fluency"]["within_doc_sd"]),"RVcon_sd":g(out["consistency"]["within_doc_sd"]),
        "RVflu_self":g(out["fluency"]["noiseless_judge_spearman"]),"RVcon_self":g(out["consistency"]["noiseless_judge_spearman"]),
        "RVflu_top":f"{out['fluency']['frac_ratings_ge_4.5']*100:.0f}"}
(TAB/"rev_summeval_autostats.tex").write_text("% auto-generated by rev_summeval.py\n"+
    "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k,v in macros.items()))
print(f"\nmost compressed aspect: {order[0]} (SD {out[order[0]]['within_doc_sd']})")
print("wrote data/rev_summeval_ceiling.json + rev_summeval_autostats.tex"); print(macros)
