#!/usr/bin/env python3
"""Cycle-5 fix (Paper A / Study 2): make the SummEval comparison fair WITHIN open models by reproducing
G-Eval's probability-weighted scoring. For gemma-4-31b (which emits a clean first-token score digit with
top-logprobs), we read the token-probability distribution over {1..5} and compute (a) the integer (argmax)
score and (b) the G-Eval-style probability-weighted expected score, from the SAME call. We then report
per-aspect summary-level Spearman for both, isolating the scoring-protocol effect from the model.
Writes data/rev_probweight.json + paper/tables/probweight_autostats.tex."""
import os, json, asyncio, sys, math
from pathlib import Path
import numpy as np, aiohttp
from scipy.stats import spearmanr
ROOT=Path(__file__).resolve().parent.parent; OUT=ROOT/"study1b"/"outputs"; DATA=ROOT/"data"; TAB=ROOT/"paper"/"tables"
sys.path.insert(0,str(ROOT/"study1b")); from harness1b import ASPECTS, load_summeval
sys.path.insert(0,str(ROOT/"study3")); from harness import BASE,KEY
MODEL="gemma-4-31b"
REP={"coherence":0.582,"consistency":0.507,"fluency":0.455,"relevance":0.547}   # reported G-Eval-4 per aspect
CKPT=OUT/"probweight.raw.jsonl"
def user(aspect,src,summ):
    return (f"Evaluation criterion:\n{ASPECTS[aspect]}\n\nSource Article:\n{src}\n\nSummary:\n{summ}\n\n"
            f"Rate {aspect} from 1 to 5. Output ONLY the integer.")
async def call(session,sem,aspect,it,fh,lock):
    body={"model":MODEL,"messages":[{"role":"system","content":"You output only a single integer 1-5."},
          {"role":"user","content":user(aspect,it["source"],it["summary"])}],
          "max_tokens":3,"temperature":0,"logprobs":True,"top_logprobs":20}
    async with sem:
        for _ in range(4):
            try:
                async with session.post(BASE+"/chat/completions",headers={"Authorization":"Bearer "+KEY},
                        json=body,timeout=aiohttp.ClientTimeout(total=90)) as r:
                    d=await r.json(); break
            except Exception: await asyncio.sleep(2)
        else: return None
    ch=(d.get("choices") or [{}])[0]; lp=ch.get("logprobs")
    toks=lp.get("content") if lp else None
    if not toks: return None
    probs={}
    for t in toks[0]["top_logprobs"]:
        tok=t["token"].strip()
        if tok in {"1","2","3","4","5"}: probs[int(tok)]=probs.get(int(tok),0)+math.exp(t["logprob"])
    if not probs: return None
    Z=sum(probs.values()); p={k:v/Z for k,v in probs.items()}
    integer=max(p,key=p.get); expected=sum(k*v for k,v in p.items())
    rec={"docid":it["docid"],"aspect":aspect,"human":it["human"][aspect],"integer":integer,"expected":expected}
    async with lock:
        fh.write(json.dumps(rec)+"\n"); fh.flush()
    return rec
async def main():
    assert KEY; items=load_summeval(None)
    done=set()
    if CKPT.exists():
        for l in open(CKPT):
            try: r=json.loads(l); done.add((r["docid"],r["aspect"]))
            except: pass
    sem=asyncio.Semaphore(16); lock=asyncio.Lock()
    with open(CKPT,"a") as fh:
        async with aiohttp.ClientSession(headers={"Content-Type":"application/json"},connector=aiohttp.TCPConnector(limit=32)) as s:
            tasks=[call(s,sem,a,it,fh,lock) for it in items for a in ASPECTS if (it["docid"],a) not in done]
            print(f"planned {len(tasks)} calls (resumed {len(done)})",flush=True)
            await asyncio.gather(*tasks)
    res=[json.loads(l) for l in open(CKPT)]   # read all (checkpointed) results
    def summ_spearman(key):
        out={}
        for a in ASPECTS:
            byd={}
            for r in res:
                if r["aspect"]==a: byd.setdefault(r["docid"],[]).append((r[key],r["human"]))
            rs=[]
            for d,ps in byd.items():
                m=[x[0] for x in ps]; h=[x[1] for x in ps]
                if len(set(m))>1 and len(set(h))>1:
                    v=spearmanr(m,h).correlation
                    if v==v: rs.append(v)
            out[a]=round(float(np.mean(rs)),3) if rs else float("nan")
        return out
    integer=summ_spearman("integer"); expected=summ_spearman("expected")
    res_obj={"model":MODEL,"n":len(res),"integer_spearman":integer,"expected_spearman":expected,"reported_geval":REP}
    print(f"gemma-4-31b SummEval ({len(res)} judgments):")
    print(f"  {'aspect':12s} {'integer':>9s} {'prob-weighted':>14s} {'reported':>10s}")
    for a in ASPECTS: print(f"  {a:12s} {integer[a]:>9.3f} {expected[a]:>14.3f} {REP[a]:>10.3f}")
    DATA.mkdir(exist_ok=True); json.dump(res_obj,open(DATA/"rev_probweight.json","w"),indent=2)
    g=lambda x:f"{x:.2f}"
    m={"PWintFlu":g(integer["fluency"]),"PWexpFlu":g(expected["fluency"]),
       "PWintCon":g(integer["consistency"]),"PWexpCon":g(expected["consistency"]),
       "PWintCoh":g(integer["coherence"]),"PWexpCoh":g(expected["coherence"])}
    (TAB/"probweight_autostats.tex").write_text("% auto-generated by rev_probweight.py\n"+"".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k,v in m.items()))
    print("wrote data/rev_probweight.json + probweight_autostats.tex"); print(m)
if __name__=="__main__": asyncio.run(main())
